const itPositions = [
  { name: "Software Developer", regex:  /(?:Software\s+Engineer|Developer)/gi },
  { name: "Web Developer", regex: /\b(?:Web\s+Developer)\b/gi },
  { name: "Frontend Developer", regex: /\b(?:Frontend\s+Developer)\b/gi },
  { name: "Backend Developer", regex: /\b(?:Backend\s+Developer)\b/gi },
  { name: "Full Stack Developer", regex: /\b(?:Full\s+Stack\s+Developer)\b/gi },
  { name: "DevOps Engineer", regex: /\b(?:DevOps\s+Engineer)\b/gi },
  { name: "Database Administrator", regex: /\b(?:Database\s+Administrator|DBA)\b/gi },
  { name: "Data Scientist", regex: /\b(?:Data\s+Scientist)\b/gi },
  { name: "Data Analyst", regex: /\b(?:Data\s+Analyst)\b/gi },
  { name: "UI/UX Designer", regex: /\b(?:UI\/UX\s+Designer)\b/gi },
  { name: "Systems Administrator", regex: /\b(?:Systems\s+Administrator)\b/gi },
  { name: "Network Engineer", regex: /\b(?:Network\s+Engineer)\b/gi },
  { name: "Security Analyst", regex: /\b(?:Security\s+Analyst)\b/gi },
  { name: "Business Analyst", regex: /\b(?:Business\s+Analyst)\b/gi },
  { name: "QA Engineer", regex: /\b(?:QA\s+Engineer|Quality\s+Assurance\s+Engineer)\b/gi },
  { name: "Machine Learning Engineer", regex: /\b(?:Machine\s+Learning\s+Engineer|ML\s+Engineer)\b/gi },
  { name: "Artificial Intelligence Engineer", regex: /\b(?:Artificial\s+Intelligence\s+Engineer|AI\s+Engineer)\b/gi },
  { name: "Cloud Engineer", regex: /\b(?:Cloud\s+Engineer)\b/gi },
  { name: "Mobile App Developer", regex: /\b(?:Mobile\s+App\s+Developer)\b/gi },
  { name: "Software Architect", regex: /\b(?:Software\s+Architect)\b/gi },
  { name: "Technical Support Engineer", regex: /\b(?:Technical\s+Support\s+Engineer)\b/gi },
  { name: "Site Reliability Engineer", regex: /\b(?:Site\s+Reliability\s+Engineer|SRE)\b/gi },
  { name: "Big Data Engineer", regex: /\b(?:Big\s+Data\s+Engineer)\b/gi },
  { name: "Embedded Systems Engineer", regex: /\b(?:Embedded\s+Systems\s+Engineer)\b/gi },
  { name: "IT Manager", regex: /\b(?:IT\s+Manager)\b/gi },
  { name: "Network Administrator", regex: /\b(?:Network\s+Administrator)\b/gi },
  { name: "Chief Technology Officer", regex: /\b(?:Chief\s+Officer|CTO)\b/gi },
  { name: "Chief Information Officer", regex: /\b(?:Chief\s+Information\s+Officer|CIO)\b/gi },
  { name: "Scrum Master", regex: /\b(?:Scrum\s+Master)\b/gi },
  { name: "Product Manager", regex: /\b(?:Product\s+Manager)\b/gi },
  { name: "Technical Writer", regex: /\b(?:Technical\s+Writer)\b/gi },
  { name: "Game Developer", regex: /\b(?:Game\s+Developer)\b/gi },
  { name: "Unity Developer", regex: /\b(?:Unity\s+Developer)\b/gi },
  { name: "Mobile App Designer", regex: /\b(?:Mobile\s+App\s+Designer)\b/gi },
  { name: "Cloud Architect", regex: /\b(?:Cloud\s+Architect)\b/gi },
  { name: "Blockchain Developer", regex: /\b(?:Blockchain\s+Developer)\b/gi },
  { name: "IoT Engineer", regex: /\b(?:IoT\s+Engineer)\b/gi },
  { name: "Automation Engineer", regex: /\b(?:Automation\s+Engineer)\b/gi },
  { name: "AR/VR Developer", regex: /\b(?:AR\/VR\s+Developer)\b/gi },
  { name: "Quality Assurance Analyst", regex: /\b(?:Quality\s+Assurance\s+Analyst|QA\s+Analyst)\b/gi },
  { name: "Network Security Engineer", regex: /\b(?:Network\s+Security\s+Engineer)\b/gi },
  { name: "Business Intelligence Analyst", regex: /\b(?:Business\s+Intelligence\s+Analyst|BI\s+Analyst)\b/gi },
  { name: "User Interface Designer", regex: /\b(?:User\s+Interface\s+Designer|UI\s+Designer)\b/gi },
  { name: "User Experience Designer", regex: /\b(?:User\s+Experience\s+Designer|UX\s+Designer)\b/gi },
  { name: "Linux System Administrator", regex: /\b(?:Linux\s+System\s+Administrator)\b/gi },
  { name: "Windows System Administrator", regex: /\b(?:Windows\s+System\s+Administrator)\b/gi },
  { name: "IT Support Specialist", regex: /\b(?:IT\s+Support\s+Specialist)\b/gi },
  { name: "Software Tester", regex: /\b(?:Software\s+Tester|Software\s+QA)\b/gi },
  { name: "IT Consultant", regex: /\b(?:IT\s+Consultant)\b/gi },
  { name: "Technical Consultant", regex: /\b(?:Technical\s+Consultant)\b/gi },
  { name: "Machine Learning Scientist", regex: /\b(?:Machine\s+Learning\s+Scientist|ML\s+Scientist)\b/gi },
  { name: "Data Engineer", regex: /\b(?:Data\s+Engineer)\b/gi },
  { name: "Data Warehouse Developer", regex: /\b(?:Data\s+Warehouse\s+Developer)\b/gi },
  { name: "Cloud Security Engineer", regex: /\b(?:Cloud\s+Security\s+Engineer)\b/gi },
  { name: "Network Architect", regex: /\b(?:Network\s+Architect)\b/gi },
  { name: "System Analyst", regex: /\b(?:System\s+Analyst)\b/gi },
  { name: "Firmware Engineer", regex: /\b(?:Firmware\s+Engineer)\b/gi },
  { name: "UX Researcher", regex: /\b(?:UX\s+Researcher)\b/gi },
  { name: "IT Trainer", regex: /\b(?:IT\s+Trainer)\b/gi },
  { name: "Cloud Solutions Architect", regex: /\b(?:Cloud\s+Solutions\s+Architect)\b/gi },
  { name: "IT Project Manager", regex: /\b(?:IT\s+Project\s+Manager)\b/gi },
  { name: "Network Operations Center (NOC) Engineer", regex: /\b(?:Network\s+Operations\s+Center\s+Engineer|NOC\s+Engineer)\b/gi },
  { name: "IT Security Specialist", regex: /\b(?:IT\s+Security\s+Specialist)\b/gi },
  { name: "UI Developer", regex: /\b(?:UI\s+Developer)\b/gi },
  { name: "UX/UI Designer", regex: /\b(?:UX\/UI\s+Designer)\b/gi },
  { name: "API Developer", regex: /\b(?:API\s+Developer)\b/gi },
  { name: "Microservices Architect", regex: /\b(?:Microservices\s+Architect)\b/gi },
  { name: "Platform Engineer", regex: /\b(?:Platform\s+Engineer)\b/gi },
  { name: "Release Engineer", regex: /\b(?:Release\s+Engineer)\b/gi },
  { name: "Software Configuration Manager", regex: /\b(?:Software\s+Configuration\s+Manager)\b/gi },
  { name: "Technology Evangelist", regex: /\b(?:Technology\s+Evangelist)\b/gi },
  { name: "Business Process Analyst", regex: /\b(?:Business\s+Process\s+Analyst)\b/gi },
  { name: "Cloud Integration Specialist", regex: /\b(?:Cloud\s+Integration\s+Specialist)\b/gi },
  { name: "API Integration Engineer", regex: /\b(?:API\s+Integration\s+Engineer)\b/gi },
  { name: "Machine Learning Specialist", regex: /\b(?:Machine\s+Learning\s+Specialist)\b/gi },
  { name: "Data Visualization Specialist", regex: /\b(?:Data\s+Visualization\s+Specialist)\b/gi },
  { name: "Database Developer", regex: /\b(?:Database\s+Developer)\b/gi },
  { name: "Application Support Analyst", regex: /\b(?:Application\s+Support\s+Analyst)\b/gi },
  { name: "Web Operations Engineer", regex: /\b(?:Web\s+Operations\s+Engineer)\b/gi },
  { name: "Cloud Migration Specialist", regex: /\b(?:Cloud\s+Migration\s+Specialist)\b/gi },
  { name: "Quality Control Engineer", regex: /\b(?:Quality\s+Control\s+Engineer)\b/gi },
  { name: "Web Content Manager", regex: /\b(?:Web\s+Content\s+Manager)\b/gi },
  { name: "Software Release Manager", regex: /\b(?:Software\s+Release\s+Manager)\b/gi },
  { name: "Technical Architect", regex: /\b(?:Technical\s+Architect)\b/gi },
  { name: "IT Auditor", regex: /\b(?:IT\s+Auditor)\b/gi },
  { name: "Network Analyst", regex: /\b(?:Network\s+Analyst)\b/gi },
  { name: "Database Analyst", regex: /\b(?:Database\s+Analyst)\b/gi },
  { name: "Integration Engineer", regex: /\b(?:Integration\s+Engineer)\b/gi },
  { name: "System Engineer", regex: /\b(?:System\s+Engineer)\b/gi },
  { name: "Computer Systems Analyst", regex: /\b(?:Computer\s+Systems\s+Analyst)\b/gi },
  { name: "Software Support Engineer", regex: /\b(?:Software\s+Support\s+Engineer)\b/gi },
  { name: "Technical Program Manager", regex: /\b(?:Technical\s+Program\s+Manager)\b/gi },
  { name: "IT Coordinator", regex: /\b(?:IT\s+Coordinator)\b/gi },
  { name: "System Administrator", regex: /\b(?:System\s+Administrator)\b/gi },
  { name: "Software Configuration Specialist", regex: /\b(?:Software\s+Configuration\s+Specialist)\b/gi },
  { name: "Infrastructure Engineer", regex: /\b(?:Infrastructure\s+Engineer)\b/gi },
  { name: "IT Analyst", regex: /\b(?:IT\s+Analyst)\b/gi },
  { name: "IT Operations Manager", regex: /\b(?:IT\s+Operations\s+Manager)\b/gi },
    { name: "Cybersecurity Analyst", regex: /\b(?:Cybersecurity\s+Analyst)\b/gi },
    { name: "Software Quality Engineer", regex: /\b(?:Software\s+Quality\s+Engineer)\b/gi },
    { name: "Cloud Solutions Engineer", regex: /\b(?:Cloud\s+Solutions\s+Engineer)\b/gi },
    { name: "Business Intelligence Developer", regex: /\b(?:Business\s+Intelligence\s+Developer)\b/gi },
    { name: "Solutions Architect", regex: /\b(?:Solutions\s+Architect)\b/gi },
    { name: "Digital Marketing Technologist", regex: /\b(?:Digital\s+Marketing\s+Technologist)\b/gi },
    { name: "Embedded Software Engineer", regex: /\b(?:Embedded\s+Software\s+Engineer)\b/gi },
    { name: "Augmented Reality Developer", regex: /\b(?:Augmented\s+Reality\s+Developer)\b/gi },
    { name: "Virtual Reality Developer", regex: /\b(?:Virtual\s+Reality\s+Developer)\b/gi },
    { name: "Ethical Hacker", regex: /\b(?:Ethical\s+Hacker)\b/gi },
    { name: "IT Business Analyst", regex: /\b(?:IT\s+Business\s+Analyst)\b/gi },
    { name: "IT Trainer", regex: /\b(?:IT\s+Trainer)\b/gi },
    { name: "Data Privacy Officer", regex: /\b(?:Data\s+Privacy\s+Officer)\b/gi },
    { name: "Software Deployment Specialist", regex: /\b(?:Software\s+Deployment\s+Specialist)\b/gi },
    { name: "IT Procurement Specialist", regex: /\b(?:IT\s+Procurement\s+Specialist)\b/gi },
    { name: "Machine Learning Ops Engineer", regex: /\b(?:Machine\s+Learning\s+Ops\s+Engineer)\b/gi },
    { name: "Remote Sensing Analyst", regex: /\b(?:Remote\s+Sensing\s+Analyst)\b/gi },
    { name: "Quantum Computing Engineer", regex: /\b(?:Quantum\s+Computing\s+Engineer)\b/gi },
    { name: "AI Ethics Specialist", regex: /\b(?:AI\s+Ethics\s+Specialist)\b/gi },
    { name: "Health IT Specialist", regex: /\b(?:Health\s+IT\s+Specialist)\b/gi },
    { name: "Robotic Process Automation Developer", regex: /\b(?:Robotic\s+Process\s+Automation\s+Developer)\b/gi },
    { name: "Remote Support Specialist", regex: /\b(?:Remote\s+Support\s+Specialist)\b/gi },
    { name: "Network Solutions Architect", regex: /\b(?:Network\s+Solutions\s+Architect)\b/gi },
    { name: "IT Accessibility Specialist", regex: /\b(?:IT\s+Accessibility\s+Specialist)\b/gi },
    { name: "Digital Transformation Consultant", regex: /\b(?:Digital\s+Transformation\s+Consultant)\b/gi },
    { name: "E-Learning Developer", regex: /\b(?:E-Learning\s+Developer)\b/gi },
    { name: "IoT Security Specialist", regex: /\b(?:IoT\s+Security\s+Specialist)\b/gi },
    { name: "AR/VR Content Creator", regex: /\b(?:AR\/VR\s+Content\s+Creator)\b/gi },
    { name: "Software Reliability Engineer", regex: /\b(?:Software\s+Reliability\s+Engineer)\b/gi },
    { name: "Data Governance Analyst", regex: /\b(?:Data\s+Governance\s+Analyst)\b/gi },
    { name: "API Security Engineer", regex: /\b(?:API\s+Security\s+Engineer)\b/gi },
    { name: "Network Reliability Engineer", regex: /\b(?:Network\s+Reliability\s+Engineer)\b/gi },
    { name: "Virtualization Engineer", regex: /\b(?:Virtualization\s+Engineer)\b/gi },
    { name: "E-Commerce Developer", regex: /\b(?:E-Commerce\s+Developer)\b/gi },
    { name: "Business Systems Analyst", regex: /\b(?:Business\s+Systems\s+Analyst)\b/gi },
    { name: "Disaster Recovery Specialist", regex: /\b(?:Disaster\s+Recovery\s+Specialist)\b/gi },
    { name: "IT Ethics Consultant", regex: /\b(?:IT\s+Ethics\s+Consultant)\b/gi },
    { name: "Cloud Governance Specialist", regex: /\b(?:Cloud\s+Governance\s+Specialist)\b/gi },
    { name: "Voice Technology Specialist", regex: /\b(?:Voice\s+Technology\s+Specialist)\b/gi },
    { name: "AI Implementation Engineer", regex: /\b(?:AI\s+Implementation\s+Engineer)\b/gi },
    { name: "Remote Infrastructure Engineer", regex: /\b(?:Remote\s+Infrastructure\s+Engineer)\b/gi },
    { name: "Quantum Software Developer", regex: /\b(?:Quantum\s+Software\s+Developer)\b/gi },
    { name: "API Integration Specialist", regex: /\b(?:API\s+Integration\s+Specialist)\b/gi },
    { name: "Web Accessibility Specialist", regex: /\b(?:Web\s+Accessibility\s+Specialist)\b/gi },
    { name: "Software Archaeologist", regex: /\b(?:Software\s+Archaeologist)\b/gi },
    { name: "Blockchain Solutions Architect", regex: /\b(?:Blockchain\s+Solutions\s+Architect)\b/gi },
    { name: "DevSecOps Engineer", regex: /\b(?:DevSecOps\s+Engineer)\b/gi },
    { name: "AI Strategy Consultant", regex: /\b(?:AI\s+Strategy\s+Consultant)\b/gi },
    { name: "Digital Accessibility Specialist", regex: /\b(?:Digital\s+Accessibility\s+Specialist)\b/gi },
    { name: "AR/VR Interaction Designer", regex: /\b(?:AR\/VR\s+Interaction\s+Designer)\b/gi },
    { name: "Wireless Network Engineer", regex: /\b(?:Wireless\s+Network\s+Engineer)\b/gi },
    { name: "Chatbot Developer", regex: /\b(?:Chatbot\s+Developer)\b/gi },
    { name: "Software Evaluator", regex: /\b(?:Software\s+Evaluator)\b/gi },
    { name: "Quantum Hardware Engineer", regex: /\b(?:Quantum\s+Hardware\s+Engineer)\b/gi },
    { name: "Blockchain Architect", regex: /\b(?:Blockchain\s+Architect)\b/gi },
    { name: "AI Process Automation Specialist", regex: /\b(?:AI\s+Process\s+Automation\s+Specialist)\b/gi },
    { name: "Digital Forensics Analyst", regex: /\b(?:Digital\s+Forensics\s+Analyst)\b/gi },
    { name: "IoT Solutions Architect", regex: /\b(?:IoT\s+Solutions\s+Architect)\b/gi },
    { name: "AR/VR UX Designer", regex: /\b(?:AR\/VR\s+UX\s+Designer)\b/gi },
    { name: "IT Compliance Analyst", regex: /\b(?:IT\s+Compliance\s+Analyst)\b/gi },
    { name: "AI Model Validator", regex: /\b(?:AI\s+Model\s+Validator)\b/gi },
    { name: "Cloud Automation Engineer", regex: /\b(?:Cloud\s+Automation\s+Engineer)\b/gi },
    { name: "API Architect", regex: /\b(?:API\s+Architect)\b/gi },
    { name: "Virtual Reality Artist", regex: /\b(?:Virtual\s+Reality\s+Artist)\b/gi },
    { name: "Network Performance Analyst", regex: /\b(?:Network\s+Performance\s+Analyst)\b/gi },
    { name: "Software Process Consultant", regex: /\b(?:Software\s+Process\s+Consultant)\b/gi },
    { name: "Blockchain Developer", regex: /\b(?:Blockchain\s+Developer)\b/gi },
    { name: "Quantum Algorithms Researcher", regex: /\b(?:Quantum\s+Algorithms\s+Researcher)\b/gi },
    { name: "AI Model Trainer", regex: /\b(?:AI\s+Model\s+Trainer)\b/gi },
    { name: "IoT Data Analyst", regex: /\b(?:IoT\s+Data\s+Analyst)\b/gi },
    { name: "AR/VR Engineer", regex: /\b(?:AR\/VR\s+Engineer)\b/gi },
    { name: "IT Governance Specialist", regex: /\b(?:IT\s+Governance\s+Specialist)\b/gi },
    { name: "AI Bias Auditor", regex: /\b(?:AI\s+Bias\s+Auditor)\b/gi },
    { name: "Cloud Billing Analyst", regex: /\b(?:Cloud\s+Billing\s+Analyst)\b/gi },
    { name: "API Developer", regex: /\b(?:API\s+Developer)\b/gi },
    { name: "Digital Twin Developer", regex: /\b(?:Digital\s+Twin\s+Developer)\b/gi },
    { name: "Blockchain Solutions Engineer", regex: /\b(?:Blockchain\s+Solutions\s+Engineer)\b/gi },
    { name: "IoT Solutions Consultant", regex: /\b(?:IoT\s+Solutions\s+Consultant)\b/gi },
    { name: "AR/VR Developer", regex: /\b(?:AR\/VR\s+Developer)\b/gi },
    { name: "IT Operations Analyst", regex: /\b(?:IT\s+Operations\s+Analyst)\b/gi },
    { name: "AI Translator", regex: /\b(?:AI\s+Translator)\b/gi },
    { name: "Cloud Capacity Planner", regex: /\b(?:Cloud\s+Capacity\s+Planner)\b/gi },
    { name: "API Integration Engineer", regex: /\b(?:API\s+Integration\s+Engineer)\b/gi },
    { name: "Digital Accessibility Consultant", regex: /\b(?:Digital\s+Accessibility\s+Consultant)\b/gi },
    { name: "Blockchain Researcher", regex: /\b(?:Blockchain\s+Researcher)\b/gi },
    { name: "IoT Security Analyst", regex: /\b(?:IoT\s+Security\s+Analyst)\b/gi },
    { name: "AR/VR Content Creator", regex: /\b(?:AR\/VR\s+Content\s+Creator)\b/gi },
    { name: "IT Process Analyst", regex: /\b(?:IT\s+Process\s+Analyst)\b/gi },
    { name: "AI Solutions Architect", regex: /\b(?:AI\s+Solutions\s+Architect)\b/gi },
    { name: "Cloud Consultant", regex: /\b(?:Cloud\s+Consultant)\b/gi },
    { name: "API Manager", regex: /\b(?:API\s+Manager)\b/gi },
    { name: "Digital Business Analyst", regex: /\b(?:Digital\s+Business\s+Analyst)\b/gi },
    { name: "Blockchain Analyst", regex: /\b(?:Blockchain\s+Analyst)\b/gi },
    { name: "IoT Solutions Engineer", regex: /\b(?:IoT\s+Solutions\s+Engineer)\b/gi },
    { name: "AR/VR Interaction Designer", regex: /\b(?:AR\/VR\s+Interaction\s+Designer)\b/gi },
    { name: "IT Process Consultant", regex: /\b(?:IT\s+Process\s+Consultant)\b/gi },
    { name: "AI Developer", regex: /\b(?:AI\s+Developer)\b/gi },
    { name: "Cloud Data Engineer", regex: /\b(?:Cloud\s+Data\s+Engineer)\b/gi },
    { name: "Application Security Specialist", regex: /\b(?:Application\s+Security\s+Specialist)\b/gi },
    { name: "Blockchain Architect", regex: /\b(?:Blockchain\s+Architect)\b/gi },
    { name: "IoT Technician", regex: /\b(?:IoT\s+Technician)\b/gi },
    { name: "AR/VR UX Designer", regex: /\b(?:AR\/VR\s+UX\s+Designer)\b/gi },
    { name: "IT Project Coordinator", regex: /\b(?:IT\s+Project\s+Coordinator)\b/gi },
    { name: "AI Engineer", regex: /\b(?:AI\s+Engineer)\b/gi },
    { name: "Cloud Data Scientist", regex: /\b(?:Cloud\s+Data\s+Scientist)\b/gi },
    { name: "Data Protection Officer", regex: /\b(?:Data\s+Protection\s+Officer)\b/gi },
    { name: "Blockchain Developer", regex: /\b(?:Blockchain\s+Developer)\b/gi },
    { name: "IoT Data Scientist", regex: /\b(?:IoT\s+Data\s+Scientist)\b/gi },
    { name: "AR/VR Engineer", regex: /\b(?:AR\/VR\s+Engineer)\b/gi },
    { name: "IT Project Manager", regex: /\b(?:IT\s+Project\s+Manager)\b/gi },
    { name: "AI Ethicist", regex: /\b(?:AI\s+Ethicist)\b/gi },
    { name: "Cloud DevOps Engineer", regex: /\b(?:Cloud\s+DevOps\s+Engineer)\b/gi },
    { name: "Database Administrator", regex: /\b(?:Database\s+Administrator)\b/gi },
    { name: "Blockchain Engineer", regex: /\b(?:Blockchain\s+Engineer)\b/gi },
    { name: "IoT Developer", regex: /\b(?:IoT\s+Developer)\b/gi },
    { name: "AR/VR Programmer", regex: /\b(?:AR\/VR\s+Programmer)\b/gi },
    { name: "IT Security Analyst", regex: /\b(?:IT\s+Security\s+Analyst)\b/gi },
    { name: "AI Expert", regex: /\b(?:AI\s+Expert)\b/gi },
    { name: "Cloud Engineer", regex: /\b(?:Cloud\s+Engineer)\b/gi },
    { name: "Database Analyst", regex: /\b(?:Database\s+Analyst)\b/gi },
    { name: "Blockchain Specialist", regex: /\b(?:Blockchain\s+Specialist)\b/gi },
    { name: "IoT Engineer", regex: /\b(?:IoT\s+Engineer)\b/gi },
    { name: "AR/VR Technician", regex: /\b(?:AR\/VR\s+Technician)\b/gi },
    { name: "IT Services Manager", regex: /\b(?:IT\s+Services\s+Manager)\b/gi },
    { name: "AI Analyst", regex: /\b(?:AI\s+Analyst)\b/gi },
    { name: "Cloud Architect", regex: /\b(?:Cloud\s+Architect)\b/gi },
    { name: "Database Developer", regex: /\b(?:Database\s+Developer)\b/gi },
    { name: "IoT Specialist", regex: /\b(?:IoT\s+Specialist)\b/gi },
    { name: "AR/VR UI Designer", regex: /\b(?:AR\/VR\s+UI\s+Designer)\b/gi },
    { name: "IT Specialist", regex: /\b(?:IT\s+Specialist)\b/gi },
    { name: "AI Assistant Developer", regex: /\b(?:AI\s+Assistant\s+Developer)\b/gi },
    { name: "Cloud Solutions Architect", regex: /\b(?:Cloud\s+Solutions\s+Architect)\b/gi },
    { name: "Data Analyst", regex: /\b(?:Data\s+Analyst)\b/gi },
    { name: "IoT Technician", regex: /\b(?:IoT\s+Technician)\b/gi },
    { name: "AR/VR UX/UI Designer", regex: /\b(?:AR\/VR\s+UX\/UI\s+Designer)\b/gi },
    { name: "IT Strategist", regex: /\b(?:IT\s+Strategist)\b/gi },
    { name: "AI Consultant", regex: /\b(?:AI\s+Consultant)\b/gi },
    { name: "Cloud Support Engineer", regex: /\b(?:Cloud\s+Support\s+Engineer)\b/gi },
    { name: "Data Architect", regex: /\b(?:Data\s+Architect)\b/gi },
    { name: "IoT UX Designer", regex: /\b(?:IoT\s+UX\s+Designer)\b/gi },
    { name: "AR/VR Developer", regex: /\b(?:AR\/VR\s+Developer)\b/gi },
    { name: "IT Support Specialist", regex: /\b(?:IT\s+Support\s+Specialist)\b/gi },
    { name: "AI Developer", regex: /\b(?:AI\s+Developer)\b/gi },
    { name: "Cloud Systems Engineer", regex: /\b(?:Cloud\s+Systems\s+Engineer)\b/gi },
    { name: "Data Engineer", regex: /\b(?:Data\s+Engineer)\b/gi },
    { name: "IoT UI Designer", regex: /\b(?:IoT\s+UI\s+Designer)\b/gi },
    { name: "AR/VR Engineer", regex: /\b(?:AR\/VR\s+Engineer)\b/gi },
    { name: "IT Technician", regex: /\b(?:IT\s+Technician)\b/gi },
    { name: "AI Engineer", regex: /\b(?:AI\s+Engineer)\b/gi },
    { name: "Cloud Security Engineer", regex: /\b(?:Cloud\s+Security\s+Engineer)\b/gi },
    { name: "Data Scientist", regex: /\b(?:Data\s+Scientist)\b/gi },
    { name: "IoT Specialist", regex: /\b(?:IoT\s+Specialist)\b/gi },
    { name: "AR/VR Interaction Designer", regex: /\b(?:AR\/VR\s+Interaction\s+Designer)\b/gi },
    { name: "IT Trainer", regex: /\b(?:IT\s+Trainer)\b/gi },
    { name: "AI Expert", regex: /\b(?:AI\s+Expert)\b/gi },
    { name: "Cloud Solutions Engineer", regex: /\b(?:Cloud\s+Solutions\s+Engineer)\b/gi },
    { name: "Data Analyst", regex: /\b(?:Data\s+Analyst)\b/gi },
    { name: "IoT Technician", regex: /\b(?:IoT\s+Technician)\b/gi },
    { name: "AR/VR UX Designer", regex: /\b(?:AR\/VR\s+UX\s+Designer)\b/gi },
    { name: "IT Analyst", regex: /\b(?:IT\s+Analyst)\b/gi },
    { name: "AI Implementation Engineer", regex: /\b(?:AI\s+Implementation\s+Engineer)\b/gi },
    { name: "Cloud Systems Engineer", regex: /\b(?:Cloud\s+Systems\s+Engineer)\b/gi },
    { name: "Data Architect", regex: /\b(?:Data\s+Architect)\b/gi },
    { name: "IoT UX Designer", regex: /\b(?:IoT\s+UX\s+Designer)\b/gi },
    { name: "AR/VR Engineer", regex: /\b(?:AR\/VR\s+Engineer)\b/gi },
    { name: "IT Technician", regex: /\b(?:IT\s+Technician)\b/gi },
    { name: "AI Ethics Specialist", regex: /\b(?:AI\s+Ethics\s+Specialist)\b/gi },
    { name: "Cloud Security Engineer", regex: /\b(?:Cloud\s+Security\s+Engineer)\b/gi },
    { name: "Database Administrator", regex: /\b(?:Database\s+Administrator)\b/gi },
    { name: "Blockchain Developer", regex: /\b(?:Blockchain\s+Developer)\b/gi },
    { name: "IoT Developer", regex: /\b(?:IoT\s+Developer)\b/gi },
    { name: "AR/VR Programmer", regex: /\b(?:AR\/VR\s+Programmer)\b/gi },
    { name: "IT Security Analyst", regex: /\b(?:IT\s+Security\s+Analyst)\b/gi },
    { name: "AI Developer", regex: /\b(?:AI\s+Developer)\b/gi },
    { name: "Cloud Engineer", regex: /\b(?:Cloud\s+Engineer)\b/gi },
    { name: "Database Analyst", regex: /\b(?:Database\s+Analyst)\b/gi },
    { name: "Blockchain Specialist", regex: /\b(?:Blockchain\s+Specialist)\b/gi },
    { name: "IoT Engineer", regex: /\b(?:IoT\s+Engineer)\b/gi },
    { name: "AR/VR Technician", regex: /\b(?:AR\/VR\s+Technician)\b/gi },
    { name: "IT Services Manager", regex: /\b(?:IT\s+Services\s+Manager)\b/gi },
    { name: "AI Analyst", regex: /\b(?:AI\s+Analyst)\b/gi },
    { name: "Cloud Architect", regex: /\b(?:Cloud\s+Architect)\b/gi },
    { name: "Database Developer", regex: /\b(?:Database\s+Developer)\b/gi },
    { name: "Blockchain Engineer", regex: /\b(?:Blockchain\s+Engineer)\b/gi },
    { name: "IoT Developer", regex: /\b(?:IoT\s+Developer)\b/gi },
    { name: "AR/VR Programmer", regex: /\b(?:AR\/VR\s+Programmer)\b/gi },
    { name: "IT Security Analyst", regex: /\b(?:IT\s+Security\s+Analyst)\b/gi },
    { name: "AI Expert", regex: /\b(?:AI\s+Expert)\b/gi },
    { name: "Cloud Engineer", regex: /\b(?:Cloud\s+Engineer)\b/gi },
    { name: "Database Analyst", regex: /\b(?:Database\s+Analyst)\b/gi },
    { name: "Blockchain Specialist", regex: /\b(?:Blockchain\s+Specialist)\b/gi },
    { name: "IoT Engineer", regex: /\b(?:IoT\s+Engineer)\b/gi },
    { name: "AR/VR Technician", regex: /\b(?:AR\/VR\s+Technician)\b/gi },
    { name: "IT Services Manager", regex: /\b(?:IT\s+Services\s+Manager)\b/gi },
    { name: "AI Analyst", regex: /\b(?:AI\s+Analyst)\b/gi },
    { name: "Cloud Architect", regex: /\b(?:Cloud\s+Architect)\b/gi },
    { name: "Database Developer", regex: /\b(?:Database\s+Developer)\b/gi },

  
];

export default itPositions;
